import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Sonic } from '@0xsonic/sdk';
import { Text } from '@chakra-ui/react';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Text fontSize="2xl" fontWeight="bold">
          Blog #1 - all about tech
        </Text>
        <Text mx="8" mb="6" noOfLines={[1, 2, 3, 4, 5, 6]}>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic quo saepe et dolorem, deserunt veritatis dolorum aperiam! Expedita ipsam blanditiis voluptatum explicabo quibusdam. Laborum quis
          recusandae adipisci voluptas nulla maxime. Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic quo saepe et dolorem, deserunt veritatis dolorum aperiam! Expedita ipsam blanditiis
          voluptatum explicabo quibusdam. Laborum quis recusandae adipisci voluptas nulla maxime. Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic quo saepe et dolorem, deserunt veritatis
          dolorum aperiam! Expedita ipsam blanditiis voluptatum explicabo quibusdam. Laborum quis recusandae adipisci voluptas nulla maxime.
        </Text>
        <Text mx="8" mb="6" noOfLines={[1, 2, 3, 4, 5, 6]}>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic quo saepe et dolorem, deserunt veritatis dolorum aperiam! Expedita ipsam blanditiis voluptatum explicabo quibusdam. Laborum quis
          recusandae adipisci voluptas nulla maxime. Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic quo saepe et dolorem, deserunt veritatis dolorum aperiam! Expedita ipsam blanditiis
          voluptatum explicabo quibusdam. Laborum quis recusandae adipisci voluptas nulla maxime. Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic quo saepe et dolorem, deserunt veritatis
          dolorum aperiam! Expedita ipsam blanditiis voluptatum explicabo quibusdam. Laborum quis recusandae adipisci voluptas nulla maxime.
        </Text>
        <Sonic context="sonictest" />
      </main>
    </>
  );
}
