name: '🚀 publish sonic-sdk'

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    name: '🚀 publish sonic'
    runs-on: ubuntu-latest
    steps:
      - name: '📚 checkout'
        uses: actions/checkout@v2.0.0
      - name: '🟢 node'
        uses: actions/setup-node@v1.4.4
        with:
          version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - name: '📦 publish'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
